rm(list = ls())
mydata <- rnorm(100)
sd(mydata)
sd(x = mydata, na.rm = FALSE)
sd(na.rm = FALSE, x = mydata)
sd(na.rm = FALSE, mydata)
y = rnorm(1)
x = rnorm(1)
args(lm)
lm(data = mydata, y - x, model = FALSE, 1:100)
lm(y - x, mydata, 1:100, model = FALSE)